load("@prelude//toolchains:demo.bzl", "system_demo_toolchains")
load("@prelude//toolchains:go.bzl", "system_go_toolchain")



# All the default toolchains, suitable for a quick demo or early prototyping.
# Most real projects should copy/paste the implementation to configure them.
system_demo_toolchains()

#remote_go_toolchain(
#    name = "go",
#    version = "1.22.0",
#    visibility = ["PUBLIC"],
#)

system_go_toolchain(
    name = "go",
    go_root = "/home/linuxbrew/.linuxbrew/Cellar/go/1.22.0/libexec/",
    visibility = ["PUBLIC"],
)